Fix for missing panel buttons
mdenet/educationplatform pull request #171
Opened 2024-01-31 21:00 UTC by barnettwilliam

Fix for missing panel buttons. Panel definitions are required to resolve any button references given in an activity config file. Button references are identified by their type that is string rather than object for Buttons.

2024-02-01 08:45 UTC, szschaler requested changes
Would be good to clean up the schema at the same time and to revert to using `.ref` so that there is a clean and consistent structure to the schema.

2024-02-01 09:07 UTC, barnettwilliam commented on platform/src/Playground.js
> +                if (typeof btn == "string"){
Ah ok yes, I'll update the documentation and revert.

2024-02-01 09:44 UTC, szschaler requested changes
I note this still doesn't update the JSON schema.

2024-02-05 09:18 UTC, barnettwilliam commented
Updated the schema in 4e419606a17bef4792cc76c1f84c2b58c51ca36e

2024-02-05 09:46 UTC, szschaler approved these changes
LGTM

2024-02-05 10:12 UTC, merged